#!/bin/bash

status=$(playerctl -p spotify status)

if [[ -z $status ]]
then
    exit -1
fi

case $1 in
    prev)
        playerctl -p spotify previous
        ;;
    next)
        playerctl -p spotify next
        ;;
    toggle-play)
        if [[ $status == "Playing" ]]
        then
            playerctl -p spotify pause
        fi

        if [[ $status == "Paused" ]]
        then
            playerctl -p spotify play
        fi
        ;;
        *)
        echo "Use: controls.sh prev|next|toggle-play"
        ;;
esac

sleep .1
pkill -RTMIN+4 waybar
