#!/usr/bin/env bash

icons=("" "" "" "" "")

geticon() {
    if [ "$status" = "disconnected" ] ; then
      icon=""
    else
      level=$(awk -v n="$signal" 'BEGIN{print int((n-1)/20)}')
      if [ "$level" -gt 4 ]; then
        level=4
      fi

      icon=${icons[$level]}

      echo $icon
    fi
}

status() {
    status=$(nmcli g | tail -n 1 | awk '{print $1}')
    signal=$(nmcli -f in-use,signal dev wifi | rg "\*" | awk '{ print $2 }')
    essid=$(nmcli -t -f NAME connection show --active | head -n1 | sed 's/\"/\\"/g')

    echo '{"essid": "'"$essid"'", "signal": "'"$signal"'", "icon": "'"$(geticon)"'"}'
}

status

ip monitor link | while read -r line; do
    status
done
