#!/bin/bash

contains() {
    if [ "${2##*"$1"*}" ]; then
        return 1
    else
        return 0
    fi
}

print_workspaces() {
    output=$(niri msg -j workspaces)
    desktops=$(echo "$output" | jq "sort_by(.idx) | .[] | .idx | tonumber")
    focused=$(echo "$output" | jq "sort_by(.idx) | .[] | select(.is_focused==true) | .idx | tonumber")

    workspace_list=()
    for d in $desktops; do
        if contains "$focused" "$d" ; then
            is_active=true
        else 
            is_active=false
        fi
        workspace_list+=("{\"name\": \"$d\", \"is_active\": $is_active}")
    done

    # Join array elements with commas
    workspace_json=$(IFS=,; echo "${workspace_list[*]}")

    echo "{\"active\": $focused, \"workspaces\": [$workspace_json]}"
}

print_workspaces

niri msg --json event-stream | while read -r line; do
    if echo "$line" | jq -e 'has("WorkspaceActivated")' > /dev/null; then
        print_workspaces
    fi
done
