#!/bin/bash

sudo apt install \
    sway kitty firefox-esr swaylock wl-clipboard pass pavucontrol fonts-font-awesome wayland-utils alsa-utils bc acpi swaybg rfkill colordiff swayidle \
    thunar transmission zathura \
    btop dunst \
    pinentry-qt gnupg2 rsync \
    libnotify-bin \
    grim slurp imagemagick \
    software-properties-common python3-launchpadlib \
    brightnessctl \
    default-jdk \
    udiskie dosfstools mtools

# update fonts
fc-cache

confirm() {
    while true; do
        read -rp "$1 (yes/no): " choice
        case "$choice" in
            yes|y) return 0 ;;
            no|n) return 1 ;;
            *) echo "Please answer yes or no." ;;
        esac
    done
}

# setup kitty
if confirm "Do you want to install Kitty?"; then
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
    cd ~/.bin
    ln -s /home/juanolon/.local/kitty.app/bin/kitty kitty
    ln -s /home/juanolon/.local/kitty.app/bin/kitten kitten
    cd -
fi

if confirm "Do you want to setup tool-sync?"; then
    cd /tmp
    wget https://github.com/chshersh/tool-sync/releases/download/v0.2.0/tool-x86_64-unknown-linux-gnu.tar.gz
    tar -xf tool-x86_64-unknown-linux-gnu.tar.gz
    sudo mv tool /usr/local/bin/tool-sync
    cd -
fi

if confirm "Do you want to setup nvim?"; then
    cd /tmp
    wget https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.tar.gz
    tar -xf nvim-linux-x86_64.tar.gz && cd nvim-linux-x86_64
    sudo mv -r share /usr/local
    sudo mv -r lib /usr/local
    sudo mv -r bin /usr/local
    cd -
fi


if confirm "Do you want to setup albert?"; then
    echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/Debian_12/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list
    curl -fsSL https://download.opensuse.org/repositories/home:manuelschneid3r/Debian_12/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_manuelschneid3r.gpg > /dev/null
    sudo apt update
    sudo apt install albert
fi

if confirm "Do you want to setup spotify?"; then
curl -sS https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
    echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
# ensure that xdg-desktop-menu entry is writen. if folder doesn't exist, it doesnt make an entry
    sudo mkdir /usr/share/desktop-directories
    sudo apt-get update && sudo apt-get install spotify-client
fi

if confirm "Do you want to setup eww?"; then
    sudo apt install libgtk-3-dev libgio2.0-cil-dev libdbusmenu-gtk3-dev libgtk-layer-shell-dev
    cd /tmp
    git clone --depth 1 https://github.com/elkowar/eww.git && cd eww
    cargo build --release --no-default-features --features=wayland
    sudo mv /home/juanolon/.cargo/bin/eww /usr/local/bin
    cd -
fi

if confirm "Do you want to setup keyboard?"; then
    source setup-keyboard
fi

if confirm "Do you want to setup bluetooth?"; then
    echo "TODO"
fi

if confirm "Do you want to setup latex?"; then
    echo "TODO"
fi

if confirm "Do you want to install other?"; then
    sudo tool-sync --config /home/juanolon/.config/tool-sync/config.toml sync
fi

if confirm "Do you want to install gamma/temperature?"; then
    cd /tmp
    git clone https://github.com/MaxVerevkin/wl-gammarelay-rs
    cd wl-gammarelay-rs && cargo install wl-gammarelay-rs --locked
    sudo mv /home/juanolon/.cargo/bin/wl-gammarelay-rs /usr/local/bin
    cd -
fi

echo "TODO: setup theme"
echo "TODO: install tpl"
# https://github.com/rose-pine/gtk?tab=readme-ov-file
echo "TODO: setup gtk theme"
