#!/bin/bash

jupyter nbextension    install jupyter_ascending --sys-prefix --py && \
jupyter nbextension     enable jupyter_ascending --sys-prefix --py && \
jupyter serverextension enable jupyter_ascending --sys-prefix --py && \
jupyter nbextension enable jupyter_ascending --py --sys-prefix && \
jupyter nbextension     list && \
jupyter serverextension list
