#!/bin/bash
##############################################################################
# screen-backlight
# -----------
# For when you are running leeenux on a Mac and it needs some help
#
# Usage:
# 	screen-backlight {up,down,total,off}
#
# :authors: Jess Frazelle, @jessfraz, @juanolon
# :date: 8 June 2015
# :version: 0.0.1
##############################################################################
set -e
set -o pipefail

# if [ $UID -ne 0 ]; then
# 	echo "Please run this program as superuser"
# 	exit 1
# fi

BLDIR=/sys/class/backlight/intel_backlight

BLFILE="$BLDIR/brightness"
BACKLIGHT=$(cat $BLFILE)
INCREMENT=20
SET_VALUE=0
MAX=$(cat "$BLDIR/max_brightness")

# Enable to play sound
PLAYSOUND=true
# Sound to play
SOUND=/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
# For how much milliseconds the notification will stay visible
TIMEOUT=1500
ID=2595

buildBar () {
    /home/juanolon/.bin/drawbar $1 $2 $3
}

sendNotification () {
    VOL=`cat /sys/class/backlight/intel_backlight/brightness`
    VOLUME=`echo "scale=2;($VOL/$MAX)*100" | bc -l | cut -d. -f1`
    echo $VOLUME
    STEP=`echo "scale=2;(($MAX/$INCREMENT)*100)/$MAX" | bc -l | cut -d. -f1`
    echo $STEP
    echo $MAX

    BODY="`buildBar $STEP $VOLUME false` $VOLUME%"
    URGENCY="normal"

    if [ $PLAYSOUND = true ]; then
        sudo -u juanolon /usr/bin/paplay -p $SOUND &
    fi

    echo "teer"
    local user="juanolon"
    local uid=$(id -u $user)
    sudo -u $user DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$uid/bus dunstify -t "$TIMEOUT" -r "$ID" -u "$URGENCY" "$BODY"
}


case $1 in

	up)
		TOTAL=$((BACKLIGHT + INCREMENT))
		if [ "$TOTAL" -gt "$MAX" ]; then
			exit 1
		fi
		SET_VALUE=1
		;;
	down)
		TOTAL=$((BACKLIGHT - INCREMENT))
		if [ "$TOTAL" -lt "1" ]; then
			exit 1
		fi
		SET_VALUE=1
		;;
	min)
		TOTAL=$INCREMENT
		SET_VALUE=1
		;;
	max)
		# TEMP_VALUE=$BACKLIGHT
		# while [ "$TEMP_VALUE" -lt "$MAX" ]; do
		# 	TEMP_VALUE=$((TEMP_VALUE + 1))
		# 	if [ "$TEMP_VALUE" -gt "$MAX" ]; then TEMP_VALUE=$MAX; fi
		# 	echo "$TEMP_VALUE" > $BLFILE
		# done
		SET_VALUE=1
		TOTAL=$MAX
		;;
	off)
		TEMP_VALUE=$BACKLIGHT
		while [ "$TEMP_VALUE" -gt "0" ]; do
			TEMP_VALUE=$((TEMP_VALUE - 1))
			if [ "$TEMP_VALUE" -lt "0" ]; then TEMP_VALUE=0; fi
			echo "$TEMP_VALUE" > $BLFILE
		done
		;;
	*)
		echo "Use: screen-backlight up|down|max|min|off"
		;;
esac

if [ "$SET_VALUE" -eq "1" ]; then
	sudo tee $BLFILE <<< $TOTAL
    sendNotification
fi
