#!/bin/bash

# scrot -o /tmp/screen.png
grim /tmp/screen.png
convert /tmp/screen.png -scale 10% -scale 1000% /tmp/screen.png
lock_pic=~/.i3/lock.png

if [[ -f $lock_pic ]]
then
    # placement x/y
    PX=0
    PY=0
    # lockscreen image info
    R=$(file $lock_pic | grep -o '[0-9]* x [0-9]*')
    RX=$(echo $R | cut -d' ' -f 1)
    RY=$(echo $R | cut -d' ' -f 3)

    outputs=$(swaymsg -t get_outputs | jq -r '.[]')
    echo $outputs | while read out;
	do
		SRX=$(echo "$out" | jq -r '.rect | .x')
		SRY=$(echo "$out" | jq -r '.rect | .y')
		SROX=$(echo "$out" | jq -r '.rect | .width')
		SROY=$(echo "$out" | jq -r '.rect | .height')
		PX=$(($SROX + $SRX/2 - $RX/2))
		PY=$(($SROY + $SRY/2 - $RY/2))
		convert /tmp/screen.png $lock_pic -geometry +$PX+$PY -composite -matte  /tmp/screen.png
		echo "done"
	done
fi

# if [[ -f $lock_pic ]]
# then
#     # placement x/y
#     PX=0
#     PY=0
#     # lockscreen image info
#     R=$(file $lock_pic | grep -o '[0-9]* x [0-9]*')
#     RX=$(echo $R | cut -d' ' -f 1)
#     RY=$(echo $R | cut -d' ' -f 3)

#     SR=$(xrandr --query | grep ' connected' | sed 's/primary //' | cut -f3 -d' ')
#     for RES in $SR
#     do
#         # monitor position/offset
#         SRX=$(echo $RES | cut -d'x' -f 1)                   # x pos
#         SRY=$(echo $RES | cut -d'x' -f 2 | cut -d'+' -f 1)  # y pos
#         SROX=$(echo $RES | cut -d'x' -f 2 | cut -d'+' -f 2) # x offset
#         SROY=$(echo $RES | cut -d'x' -f 2 | cut -d'+' -f 3) # y offset
#         PX=$(($SROX + $SRX/2 - $RX/2))
#         PY=$(($SROY + $SRY/2 - $RY/2))

#         convert /tmp/screen.png $lock_pic -geometry +$PX+$PY -composite -matte  /tmp/screen.png
#         echo "done"
#     done
# fi
# dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop
# i3lock  -I 10 -d -e -u -n -i /tmp/screen.png
# playerctl stop
# i3lock -e -i /tmp/screen.png
swaylock -f -i /tmp/screen.png
